# Generated by Django 3.0.4 on 2023-02-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtin', '0011_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
