# Generated by Django 3.0.4 on 2023-02-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtin', '0013_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
