# Generated by Django 3.0.4 on 2023-02-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtin', '0016_gs1rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GS1Rules',
        ),
    ]
