# Generated by Django 3.0.4 on 2023-02-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtin', '0020_gs1rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GS1Rules',
        ),
    ]
